service: slack

custom:
  DYNAMODB_TABLE: ${file(env.yml):DYNAMODB_TABLE}-${opt:stage}

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SIGNING_SECRET: ${file(env.yml):SIGNING_SECRET}
    DYNAMODB_TABLE: ${self:custom.DYNAMODB_TABLE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["slackTable", "Arn"] }
  region: ${file(env.yml):REGION}

functions:
  slack:
    handler: handler.slack
    events:
      - http:
          path: slack
          method: post

resources:
  Resources:
    slackTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: messageTs
            AttributeType: S
        KeySchema:
          - AttributeName: messageTs
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
